"""Added Candles Table With composite key

Revision ID: 1607253a37cf
Revises: 808a1458d6b2
Create Date: 2026-08-14 11:58:01.536432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1607253a37cf'
down_revision: Union[str, Sequence[str], None] = '808a1458d6b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candles',
    sa.Column('window_start', sa.DateTime(), nullable=False),
    sa.Column('timeframe', sa.String(length=5), nullable=False),
    sa.Column('ticker', sa.String(length=5), nullable=False),
    sa.Column('transactions', sa.Integer(), nullable=False),
    sa.Column('close', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('high', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('low', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('open', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('session_end_date', sa.DateTime(), nullable=False),
    sa.Column('settlement_price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('dollar_volume', sa.Integer(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('window_start', 'timeframe', 'ticker')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candles')
    # ### end Alembic commands ###
