"""Updated the Nuallability of settlement_price

Revision ID: 24c388ca87c6
Revises: bc50ed60d291
Create Date: 2026-08-15 08:09:39.743327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24c388ca87c6'
down_revision: Union[str, Sequence[str], None] = 'bc50ed60d291'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candles', 'settlement_price',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candles', 'settlement_price',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               nullable=False)
    # ### end Alembic commands ###
