"""add symbol, contract_month, contract_year to candles

Revision ID: 498971e88fd1
Revises: 24c388ca87c6
Create Date: 2026-08-15 11:34:06.099278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '498971e88fd1'
down_revision: Union[str, Sequence[str], None] = '24c388ca87c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candles', sa.Column('symbol', sa.String(length=5), nullable=False))
    op.add_column('candles', sa.Column('contract_month', sa.String(length=2), nullable=False))
    op.add_column('candles', sa.Column('contract_year', sa.Integer(), nullable=False))
    op.alter_column('candles', 'ticker',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.String(length=7),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candles', 'ticker',
               existing_type=sa.String(length=7),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False)
    op.drop_column('candles', 'contract_year')
    op.drop_column('candles', 'contract_month')
    op.drop_column('candles', 'symbol')
    # ### end Alembic commands ###
